packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - '@nestjs/core'
  - argon2
  - esbuild
  - nx
ignoredBuiltDependencies:
  - unrs-resolver
allowBuilds:
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  nx: true
  unrs-resolver: false
